allowBuilds:
  sharp: true
  unrs-resolver: true
overrides:
  next>postcss: 8.5.22
  next>sharp: 0.35.0
  minimatch@3.1.5>brace-expansion: 5.0.8
  minimatch@10.2.5>brace-expansion: 5.0.8
onlyBuiltDependencies:
  - sharp
  - unrs-resolver
