import type { CmsContentRecord, CmsPage } from "@/lib/cms-types";

const defaultWorkspaceId = "workspace-baba-muyi-family-archive";
const defaultLegacyProfileId = "legacy-profile-baba-muyi";
const implementedAt = "2026-08-06T00:00:00.000Z";

export const babaMuyiEditorialPageOverrides: Array<Partial<CmsPage> & { id: string; path: string }> = [
  {
    id: "page-timeline",
    path: "/timeline",
    eyebrow: "Historical Timeline",
    title: "Baba Muyi Historical Timeline",
    description:
      "A careful chronology of broad life phases supported by the approved biography, family recollections, and archive notes. Exact years are used only where the approved source supplies them.",
    body:
      "This timeline uses broad historical phases where exact dates are not yet verified. Additional documents, photographs, and testimony can be added through the CMS after editorial review.",
    seoTitle: "Baba Muyi Historical Timeline | LegacyHub",
    metaDescription:
      "Explore broad historical phases from the life of Alhaji Tioluwalase “Baba Muyi” Majekodunmi, including family roots, Bariga, transport enterprise, community service, and legacy.",
    verificationStatus: "family_memory",
    updatedAt: implementedAt
  },
  {
    id: "page-documentaries",
    path: "/documentaries",
    eyebrow: "Documentary Archive",
    title: "Baba Muyi Documentaries",
    description:
      "Watch approved documentary records connected to Baba Muyi’s life, family memories, historical records, photographs, transport heritage, and continuing legacy archive.",
    body:
      "Approved documentary recordings are available below. Additional transcripts, subtitles, clips, and supporting records will be published after verification and editorial approval.",
    cards: [
      {
        id: "documentary-biography-link",
        title: "Relationship to the biography",
        description: "The documentary work supports the approved biography by preserving narration, memories, records, photographs, and context.",
        href: "/biography"
      },
      {
        id: "documentary-transcripts-link",
        title: "Transcripts and clips",
        description: "Transcripts, subtitles, trailers, and clips remain review-controlled until approved for public release.",
        href: "/transcripts"
      }
    ],
    seoTitle: "Baba Muyi Documentaries | Baba Muyi Legacy",
    metaDescription:
      "Watch approved documentary records exploring Baba Muyi’s biography, family memories, transport heritage, community service, and enduring legacy.",
    verificationStatus: "family_memory",
    updatedAt: implementedAt
  },
  {
    id: "page-gallery",
    path: "/gallery",
    eyebrow: "Photo Archive",
    title: "Baba Muyi Photo Archive",
    description:
      "Published photographs and albums connected to Baba Muyi’s family life, Bariga history, Iboogun and Abeokuta roots, transport enterprise, documentary work, and community relationships.",
    body:
      "Images should appear only with approved captions, alt text, source notes, permissions, privacy review, and verification status. The archive does not use stock photographs as historical evidence.",
    cards: [
      { id: "gallery-portraits", title: "Baba Muyi portraits", description: "Approved portraits and identity images with source notes and permissions.", href: "/portraits" },
      { id: "gallery-family", title: "Family life", description: "Family photographs published only when privacy and consent requirements are satisfied.", href: "/family" },
      { id: "gallery-transport", title: "Transport heritage", description: "Bolekaja, TIOLUWA LASE, Molue, route, and road-memory material where evidence is available.", href: "/transport-gallery" }
    ],
    seoTitle: "Baba Muyi Photo Archive | LegacyHub",
    metaDescription:
      "Explore approved Baba Muyi Legacy photographs and albums, including family life, transport heritage, Bariga, Iboogun, Abeokuta roots, and documentary preservation materials.",
    verificationStatus: "family_memory",
    updatedAt: implementedAt
  },
  {
    id: "page-lessons",
    path: "/lessons",
    eyebrow: "Legacy Lessons",
    title: "Legacy Lessons from Baba Muyi",
    description:
      "Editorial lessons drawn from the approved biography, presented as reflections rather than invented quotations.",
    body:
      "These lessons are reflections drawn from Baba Muyi’s documented life and family history. They are not presented as his direct words unless a verified source records them as such.",
    seoTitle: "Legacy Lessons from Baba Muyi | LegacyHub",
    metaDescription:
      "Read values and lessons drawn from the approved biography of Alhaji Tioluwalase “Baba Muyi” Majekodunmi, including service, hard work, responsibility, discernment, and preservation.",
    verificationStatus: "family_memory",
    updatedAt: implementedAt
  },
  {
    id: "page-tributes",
    path: "/tributes",
    eyebrow: "Community Memories",
    title: "Share a Memory",
    description:
      "A review-first place for family members, friends, former workers, neighbours, passengers, and community members to contribute memories of Baba Muyi.",
    body:
      "No public tribute is published automatically. Submissions are reviewed for consent, privacy, attribution, relevance, and family sensitivity before they appear in the public archive.",
    seoTitle: "Share a Memory of Baba Muyi | LegacyHub",
    metaDescription:
      "Submit a reviewed memory, tribute, correction, photograph lead, or context note for the Baba Muyi Legacy archive.",
    verificationStatus: "family_memory",
    updatedAt: implementedAt
  },
  {
    id: "page-curator",
    path: "/curator",
    eyebrow: "About the Archive",
    title: "About Baba Muyi Legacy",
    description:
      "A concise introduction to Alhaji Tioluwalase “Baba Muyi” Majekodunmi, the purpose of the archive, and the role of LegacyHub.",
    body:
      "Baba Muyi Legacy preserves the life of Alhaji Tioluwalase “Baba Muyi” Majekodunmi: an entrepreneur, transport pioneer, father of twenty-seven children, family patriarch, community figure, high chief, and humanitarian whose story is rooted in Abeokuta, Iboogun, Bariga, family responsibility, service, and transport enterprise. The archive was initiated by Azeez Adeyemi Majekodunmi to protect family recollections, documentary material, photographs, and public memory for future generations.",
    cards: [
      {
        id: "about-baba-muyi",
        title: "Baba Muyi",
        description: "The archive presents his story with respect for family memory, documentary evidence, and careful source notes.",
        href: "/biography"
      },
      {
        id: "about-legacyhub",
        title: "Powered by LegacyHub",
        description: "LegacyHub provides the reusable platform architecture while Baba Muyi Legacy remains the flagship archive.",
        href: "/legacyhub/flagship-archive"
      },
      {
        id: "about-founder",
        title: "Preservation work",
        description: "Azeez Adeyemi Majekodunmi is preserving the archive through family recollections, writings, documentary material, and reviewed contributions.",
        href: "/tributes"
      }
    ],
    seoTitle: "About Alhaji Tioluwalase “Baba Muyi” Majekodunmi",
    metaDescription:
      "Learn about Baba Muyi Legacy, the archive preserving Alhaji Tioluwalase “Baba Muyi” Majekodunmi’s life, family history, transport heritage, community service, and documentary materials.",
    verificationStatus: "family_memory",
    updatedAt: implementedAt
  },
  {
    id: "page-contact",
    path: "/contact",
    eyebrow: "Contact",
    title: "Contact Baba Muyi Legacy",
    description:
      "Contact the archive team about family memories, photographs, documentary material, corrections, source notes, permissions, or LegacyHub platform enquiries.",
    body:
      "Contributions should include clear attribution, context, and any known privacy or permission limits. The archive team reviews material before publication.",
    verificationStatus: "family_memory",
    updatedAt: implementedAt
  }
];

export const babaMuyiEditorialContentRecords: CmsContentRecord[] = [
  {
    id: "timeline-birth-abeokuta-roots",
    workspaceId: defaultWorkspaceId,
    legacyProfileId: defaultLegacyProfileId,
    kind: "timeline_event",
    title: "Birth and family roots in Abeokuta",
    slug: "birth-abeokuta-roots",
    summary: "The approved biography records that Baba Muyi was born in Abeokuta, in present-day Ogun State, Nigeria.",
    body: "This entry is based on the approved biography. No exact birth date is published here because the current public source does not provide one.",
    status: "published",
    visibility: "public",
    verificationStatus: "family_memory",
    sortOrder: 1,
    relatedPath: "/timeline",
    dateLabel: "Undated early life",
    category: "Family roots",
    createdAt: implementedAt,
    updatedAt: implementedAt
  },
  {
    id: "timeline-iboogun-family-connection",
    workspaceId: defaultWorkspaceId,
    legacyProfileId: defaultLegacyProfileId,
    kind: "timeline_event",
    title: "Ancestral connection to Iboogun",
    slug: "iboogun-family-connection",
    summary: "The biography connects Baba Muyi’s family roots to Iboogun, where his parents lived and were eventually buried.",
    body: "This broad phase preserves the family-root connection without adding unverified dates, addresses, or genealogy details.",
    status: "published",
    visibility: "public",
    verificationStatus: "family_memory",
    sortOrder: 2,
    relatedPath: "/timeline",
    dateLabel: "Undated early life",
    category: "Family roots",
    createdAt: implementedAt,
    updatedAt: implementedAt
  },
  {
    id: "timeline-cultural-formation",
    workspaceId: defaultWorkspaceId,
    legacyProfileId: defaultLegacyProfileId,
    kind: "timeline_event",
    title: "Early life and cultural formation",
    slug: "early-life-cultural-formation",
    summary: "His upbringing is described through Yoruba family values, respect for elders, communal responsibility, hard work, and oral tradition.",
    body: "The archive treats this as a values and formation phase rather than an exact-dated event.",
    status: "published",
    visibility: "public",
    verificationStatus: "family_memory",
    sortOrder: 3,
    relatedPath: "/timeline",
    dateLabel: "Undated early life",
    category: "Formation",
    createdAt: implementedAt,
    updatedAt: implementedAt
  },
  {
    id: "timeline-journey-to-bariga",
    workspaceId: defaultWorkspaceId,
    legacyProfileId: defaultLegacyProfileId,
    kind: "timeline_event",
    title: "Journey from Iboogun to Bariga",
    slug: "journey-from-iboogun-to-bariga",
    summary: "As a young man, Baba Muyi left Iboogun and moved to Bariga, Lagos, beginning a defining chapter of his life.",
    body: "The biography describes Bariga as a developing area at the time, with undeveloped land, narrow roads, footpaths, and surrounding vegetation.",
    status: "published",
    visibility: "public",
    verificationStatus: "family_memory",
    sortOrder: 4,
    relatedPath: "/timeline",
    dateLabel: "Undated young adulthood",
    category: "Bariga",
    createdAt: implementedAt,
    updatedAt: implementedAt
  },
  {
    id: "timeline-life-in-bariga",
    workspaceId: defaultWorkspaceId,
    legacyProfileId: defaultLegacyProfileId,
    kind: "timeline_event",
    title: "Establishing a life in Bariga",
    slug: "establishing-life-in-bariga",
    summary: "Bariga became central to Baba Muyi’s family life, business activities, public identity, and historical legacy.",
    body: "This phase is intentionally broad because the approved source does not provide exact dates for settlement milestones.",
    status: "published",
    visibility: "public",
    verificationStatus: "family_memory",
    sortOrder: 5,
    relatedPath: "/timeline",
    dateLabel: "Undated Bariga years",
    category: "Bariga",
    createdAt: implementedAt,
    updatedAt: implementedAt
  },
  {
    id: "timeline-entry-transportation",
    workspaceId: defaultWorkspaceId,
    legacyProfileId: defaultLegacyProfileId,
    kind: "timeline_event",
    title: "Entry into transportation",
    slug: "entry-into-transportation",
    summary: "Baba Muyi entered transportation during an important period in the development of public transport in Lagos.",
    body: "The biography frames transportation as both a business opportunity and a necessary public service.",
    status: "published",
    visibility: "public",
    verificationStatus: "family_memory",
    sortOrder: 6,
    relatedPath: "/timeline",
    dateLabel: "Undated enterprise years",
    category: "Transport",
    createdAt: implementedAt,
    updatedAt: implementedAt
  },
  {
    id: "timeline-bolekaja-period",
    workspaceId: defaultWorkspaceId,
    legacyProfileId: defaultLegacyProfileId,
    kind: "timeline_event",
    title: "Bolekaja transport period",
    slug: "bolekaja-transport-period",
    summary: "His early transport work is associated with the wooden passenger vehicles popularly known as Bolekaja.",
    body: "The entry records the Bolekaja period without inventing fleet sizes, exact routes, publication dates, or vehicle counts.",
    status: "published",
    visibility: "public",
    verificationStatus: "family_memory",
    sortOrder: 7,
    relatedPath: "/timeline",
    dateLabel: "Undated transport phase",
    category: "Bolekaja",
    createdAt: implementedAt,
    updatedAt: implementedAt
  },
  {
    id: "timeline-tioluwalase-transport",
    workspaceId: defaultWorkspaceId,
    legacyProfileId: defaultLegacyProfileId,
    kind: "timeline_event",
    title: "Expansion under TIOLUWA LASE",
    slug: "expansion-under-tioluwalase",
    summary: "As Lagos transport changed, his vehicles carried the inscription TIOLUWA LASE, a name associated with his business and identity.",
    body: "The biography connects the TIOLUWA LASE transport identity to larger buses and routes including Bariga, Yaba, Oyingbo, Idumota, and surrounding areas.",
    status: "published",
    visibility: "public",
    verificationStatus: "family_memory",
    sortOrder: 8,
    relatedPath: "/timeline",
    dateLabel: "Undated transport phase",
    category: "TIOLUWA LASE",
    createdAt: implementedAt,
    updatedAt: implementedAt
  },
  {
    id: "timeline-community-leadership-service",
    workspaceId: defaultWorkspaceId,
    legacyProfileId: defaultLegacyProfileId,
    kind: "timeline_event",
    title: "Community leadership and service",
    slug: "community-leadership-service",
    summary: "Baba Muyi was recognised as a high chief and community figure whose influence was built through achievement, accessibility, generosity, and service.",
    body: "The biography describes people approaching him for advice, assistance, introductions, mediation, and support.",
    status: "published",
    visibility: "public",
    verificationStatus: "family_memory",
    sortOrder: 9,
    relatedPath: "/timeline",
    dateLabel: "Undated community life",
    category: "Community",
    createdAt: implementedAt,
    updatedAt: implementedAt
  },
  {
    id: "timeline-family-growth",
    workspaceId: defaultWorkspaceId,
    legacyProfileId: defaultLegacyProfileId,
    kind: "timeline_event",
    title: "Growth of his family",
    slug: "growth-of-his-family",
    summary: "The approved biography records Baba Muyi as the father of twenty-seven children and the central figure of a large family household.",
    body: "This entry records family responsibility and household leadership without publishing private living-person details.",
    status: "published",
    visibility: "public",
    verificationStatus: "family_memory",
    sortOrder: 10,
    relatedPath: "/timeline",
    dateLabel: "Undated family life",
    category: "Family",
    createdAt: implementedAt,
    updatedAt: implementedAt
  },
  {
    id: "timeline-later-life-resilience",
    workspaceId: defaultWorkspaceId,
    legacyProfileId: defaultLegacyProfileId,
    kind: "timeline_event",
    title: "Later-life changes and resilience",
    slug: "later-life-changes-resilience",
    summary: "The biography records later-life challenges involving trust, responsibility, business decline, disputed interests, and material loss.",
    body: "This entry follows the editorial safety rule: family recollections about painful or disputed matters are not presented as settled legal conclusions.",
    status: "published",
    visibility: "public",
    verificationStatus: "family_memory",
    sortOrder: 11,
    relatedPath: "/timeline",
    dateLabel: "Later years",
    category: "Resilience",
    createdAt: implementedAt,
    updatedAt: implementedAt
  },
  {
    id: "timeline-death-continuing-legacy",
    workspaceId: defaultWorkspaceId,
    legacyProfileId: defaultLegacyProfileId,
    kind: "timeline_event",
    title: "Death and continuing legacy",
    slug: "death-continuing-legacy",
    summary: "Baba Muyi died in 2008, but his influence continues through family memories, photographs, documents, oral testimonies, and lessons.",
    body: "This date is included because it is supplied by the approved biography and existing legacy-profile record.",
    status: "published",
    visibility: "public",
    verificationStatus: "family_memory",
    sortOrder: 12,
    relatedPath: "/timeline",
    dateLabel: "2008",
    category: "Legacy",
    createdAt: implementedAt,
    updatedAt: implementedAt
  },
  {
    id: "lesson-leadership-service",
    workspaceId: defaultWorkspaceId,
    legacyProfileId: defaultLegacyProfileId,
    kind: "lesson",
    title: "Leadership begins with service",
    slug: "leadership-begins-with-service",
    summary: "Baba Muyi’s standing in the community was connected to accessibility, advice, assistance, and practical service.",
    body: "Historical connection: the biography describes his house and office as places where family, business, and community matters were discussed. Practical lesson: influence should be measured by the people one serves, not only by position or title. Related chapter: Beyond Business: A Leader Who Served His Community.",
    status: "published",
    visibility: "public",
    verificationStatus: "family_memory",
    sortOrder: 1,
    relatedPath: "/lessons",
    category: "Service",
    createdAt: implementedAt,
    updatedAt: implementedAt
  },
  {
    id: "lesson-hard-work-opportunity",
    workspaceId: defaultWorkspaceId,
    legacyProfileId: defaultLegacyProfileId,
    kind: "lesson",
    title: "Hard work creates opportunity",
    slug: "hard-work-creates-opportunity",
    summary: "His movement into transportation shows courage, practical intelligence, and enterprise.",
    body: "Historical connection: Baba Muyi recognised transportation as both a business opportunity and a public service. Practical lesson: work can create independence and open doors for others. Related chapter: Building a Dream: The Birth of an Entrepreneur.",
    status: "published",
    visibility: "public",
    verificationStatus: "family_memory",
    sortOrder: 2,
    relatedPath: "/lessons",
    category: "Enterprise",
    createdAt: implementedAt,
    updatedAt: implementedAt
  },
  {
    id: "lesson-success-responsibility",
    workspaceId: defaultWorkspaceId,
    legacyProfileId: defaultLegacyProfileId,
    kind: "lesson",
    title: "Success carries responsibility",
    slug: "success-carries-responsibility",
    summary: "The biography presents business success as something that created employment and supported relatives, workers, and associates.",
    body: "Historical connection: his transport business supported drivers, conductors, mechanics, assistants, relatives, and others. Practical lesson: success is strongest when it helps people rise. Related chapter: From Bolekaja to TIOLUWA LASE: A Legacy on the Roads of Lagos.",
    status: "published",
    visibility: "public",
    verificationStatus: "family_memory",
    sortOrder: 3,
    relatedPath: "/lessons",
    category: "Responsibility",
    createdAt: implementedAt,
    updatedAt: implementedAt
  },
  {
    id: "lesson-good-name",
    workspaceId: defaultWorkspaceId,
    legacyProfileId: defaultLegacyProfileId,
    kind: "lesson",
    title: "A good name is more valuable than possessions",
    slug: "good-name-more-valuable-than-possessions",
    summary: "The biography reflects that material wealth can disappear while character and human influence can remain.",
    body: "Historical connection: later-life losses did not erase the respect people held for him or the memories of lives he touched. Practical lesson: build character that outlasts material circumstances. Related chapter: Later Years: Resilience Through Change.",
    status: "published",
    visibility: "public",
    verificationStatus: "family_memory",
    sortOrder: 4,
    relatedPath: "/lessons",
    category: "Character",
    createdAt: implementedAt,
    updatedAt: implementedAt
  },
  {
    id: "lesson-kindness-wisdom",
    workspaceId: defaultWorkspaceId,
    legacyProfileId: defaultLegacyProfileId,
    kind: "lesson",
    title: "Kindness should be guided by wisdom",
    slug: "kindness-guided-by-wisdom",
    summary: "The biography treats generosity as a strength that also required discernment, documentation, and protection.",
    body: "Historical connection: family recollections describe painful experiences involving trust, responsibility, and disputed interests. Practical lesson: kindness should walk with accountability, records, boundaries, and wise counsel. Related chapter: The Price of Blind Trust.",
    status: "published",
    visibility: "public",
    verificationStatus: "family_memory",
    sortOrder: 5,
    relatedPath: "/lessons",
    category: "Discernment",
    createdAt: implementedAt,
    updatedAt: implementedAt
  },
  {
    id: "lesson-family-sacrifice",
    workspaceId: defaultWorkspaceId,
    legacyProfileId: defaultLegacyProfileId,
    kind: "lesson",
    title: "Family responsibility requires sacrifice",
    slug: "family-responsibility-requires-sacrifice",
    summary: "Baba Muyi’s role as father of twenty-seven children and family patriarch carried broad responsibility.",
    body: "Historical connection: his responsibilities extended across wives, children, relatives, workers, visitors, and the wider community. Practical lesson: family leadership requires care, sacrifice, patience, and accountability. Related chapter: Family, Responsibility and Sacrifice.",
    status: "published",
    visibility: "public",
    verificationStatus: "family_memory",
    sortOrder: 6,
    relatedPath: "/lessons",
    category: "Family",
    createdAt: implementedAt,
    updatedAt: implementedAt
  },
  {
    id: "lesson-community-consistency",
    workspaceId: defaultWorkspaceId,
    legacyProfileId: defaultLegacyProfileId,
    kind: "lesson",
    title: "Community leadership is built through consistent actions",
    slug: "community-leadership-consistent-actions",
    summary: "His community standing came from visible work, generosity, relationships, and practical assistance over time.",
    body: "Historical connection: people approached him for advice, assistance, introductions, mediation, and support. Practical lesson: leadership is built through repeated service, not a single public gesture. Related chapter: Beyond Business: A Leader Who Served His Community.",
    status: "published",
    visibility: "public",
    verificationStatus: "family_memory",
    sortOrder: 7,
    relatedPath: "/lessons",
    category: "Community",
    createdAt: implementedAt,
    updatedAt: implementedAt
  },
  {
    id: "lesson-preserve-history",
    workspaceId: defaultWorkspaceId,
    legacyProfileId: defaultLegacyProfileId,
    kind: "lesson",
    title: "History must be preserved before memories disappear",
    slug: "history-must-be-preserved",
    summary: "The biography explains that important family history can be forgotten or rewritten without records, photographs, oral testimonies, and verification.",
    body: "Historical connection: Baba Muyi Legacy exists to gather biography, family memories, photographs, documents, oral histories, and documentary material. Practical lesson: preserve meaningful records while people can still explain them. Related chapter: An Enduring Legacy.",
    status: "published",
    visibility: "public",
    verificationStatus: "family_memory",
    sortOrder: 8,
    relatedPath: "/lessons",
    category: "Preservation",
    createdAt: implementedAt,
    updatedAt: implementedAt
  },
  {
    id: "lesson-technology-dignity",
    workspaceId: defaultWorkspaceId,
    legacyProfileId: defaultLegacyProfileId,
    kind: "lesson",
    title: "Technology should support human memory and dignity",
    slug: "technology-memory-dignity",
    summary: "LegacyHub is the platform layer behind the archive, but the human story remains the reason for the technology.",
    body: "Historical connection: This lesson arises from the decision to preserve Baba Muyi’s history through LegacyHub. Technology supports the archive, but his life, character, relationships, and human influence remain at the centre of the story. Practical lesson: technology should serve memory, dignity, culture, and humanity. Related chapter: Preserving His Story Through LegacyHub.",
    status: "published",
    visibility: "public",
    verificationStatus: "family_memory",
    sortOrder: 9,
    relatedPath: "/lessons",
    category: "Preservation",
    createdAt: implementedAt,
    updatedAt: implementedAt
  },
  {
    id: "documentary-baba-muyi-legacy",
    workspaceId: defaultWorkspaceId,
    legacyProfileId: defaultLegacyProfileId,
    kind: "documentary",
    title: "The Biography of Alhaji Tioluwalase “Baba Muyi” Majekodunmi — Humanity, Compassion and Discipline",
    slug: "the-biography-of-alhaji-tioluwalase-baba-muyi-majekodunmi",
    summary:
      "A documentary biography exploring the life, family history, entrepreneurship, community service, transport heritage, challenges, and enduring legacy of Alhaji Tioluwalase “Baba Muyi” Majekodunmi.",
    body:
      "Public YouTube URL: https://www.youtube.com/watch?v=BW_t_CwFV60&t=72s",
    status: "published",
    visibility: "public",
    verificationStatus: "family_memory",
    sortOrder: 1,
    relatedPath: "/documentaries",
    externalUrl: "https://www.youtube.com/watch?v=BW_t_CwFV60&t=72s",
    category: "Biography Documentary",
    createdAt: implementedAt,
    updatedAt: implementedAt
  },
  {
    id: "documentary-baba-muyi-legacy-additional-record",
    workspaceId: defaultWorkspaceId,
    legacyProfileId: defaultLegacyProfileId,
    kind: "documentary",
    title: "The Legacy of Alhaji Tioluwalase “Baba Muyi” Majekodunmi — From Bariga Forest to Fleet",
    slug: "the-legacy-of-alhaji-tioluwalase-baba-muyi-majekodunmi-from-bariga-forest-to-fleet",
    summary:
      "An additional documentary record connected to Baba Muyi’s biography, family memories, historical experiences, and continuing legacy archive.",
    body:
      "Public YouTube URL: https://www.youtube.com/watch?v=pszhSQ9SaJo&t=19s",
    status: "published",
    visibility: "public",
    verificationStatus: "family_memory",
    sortOrder: 2,
    relatedPath: "/documentaries",
    externalUrl: "https://www.youtube.com/watch?v=pszhSQ9SaJo&t=19s",
    category: "Documentary Record",
    createdAt: implementedAt,
    updatedAt: implementedAt
  },
  {
    id: "gallery-album-archive-categories",
    workspaceId: defaultWorkspaceId,
    legacyProfileId: defaultLegacyProfileId,
    kind: "gallery_album",
    title: "Archive image categories",
    slug: "archive-image-categories",
    summary:
      "The gallery is organised around portraits, family life, Bariga, Iboogun and Abeokuta roots, Bolekaja transport, TIOLUWA LASE buses, community relationships, documentary production, and family preservation materials.",
    body:
      "This record describes the approved gallery structure only. It does not invent image counts, captions, names, dates, locations, or vehicle details.",
    status: "published",
    visibility: "public",
    verificationStatus: "family_memory",
    sortOrder: 1,
    relatedPath: "/gallery",
    category: "Gallery structure",
    createdAt: implementedAt,
    updatedAt: implementedAt
  }
];
